### ISSUE TITLE
Credibility labels revision

### ISSUE THREAD

**Issue by aleixac** [co-inform/gateway-api#7]
The credibility labels that the browser plugin is expecting doesn't seem to match the ones specified in the API gateway.

Here is a list of the plugin expected labels:
[ accurate, accurate_with_considerations, unsubstantiated, inaccurate_with_considerations, inaccurate, not_verifiable_post ]

Here a list of the specified API "final_credibility" labels:
[ credible, mostly credible, credibility uncertain, mostly not credible, not credible, not verifiable ]

Also we find that from time to time the browser plugin is receiving the unspecified label: "not credible post".

**Comment by andreasjberg** [comment]
The Gateway now uses the labels defined in the api

**Comment by rdenaux** [comment]
What is the difference, from the plugin's perspective, between "expected labels" and "final_credibility labels"?
